// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int rep = Integer.parseInt(args[0]);

        int i = 0;
		int countAbove = 0;
		int countbelow = 0;
		while(i < rep){
			if (Math.random() > 0.5){
				 countAbove++;
			}else{
				countbelow++;
		}
		i++;
	}
	System.out.println("> 0.5: " + countAbove + " times");
	System.out.println("<= 0.5: " + countbelow + " times");

	if(countAbove != 0 && countbelow != 0 ){

	double ratio = (double)Math.min(countbelow,countAbove)/Math.max(countbelow,countAbove);
	System.out.println("Ratio: " + ratio);
  }
 }
}
